[package]
name = "libaosc"
version = "0.1.0"
edition = "2021"
description = "AOSC Rust useful library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
reqwest = { version = "0.11", default-features = false, optional = true }
async-compression = { version = "0.4", features = ["tokio", "xz"], optional = true }
tokio = { version = "1.34", features = ["fs"], optional = true }
thiserror = "1.0"
oma-debcontrol = "0.3"
xz2 = { version = "0.1", optional = true }

[features]
default = ["download", "blocking", "async"]
download = ["dep:reqwest"]
blocking = ["reqwest/blocking", "dep:xz2"]
async = ["dep:async-compression", "dep:tokio"]
